### ISSUE TITLE
Use Option<ExternalResolver> or export NoResolvers from canonical_host

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/canonical#57]
Currently we always ask for a resolver in our `query` and `transaction` calls. The problem is that we don't always need external resolvers.

Therefore, it might be nice to take one of these two approaches so that we don't need to create dummy resolvers in other repos that want to use canonical.

**Comment by ZER0** [comment]
As discussed already in the stand up this morning:
The first implementation of `ExternalResolver` used a `Option`, but the compiler wasn't able to properly understand the type / lifetime when `None` was passed. It would be a similar problem to what `MemoryHolder` had, to be clearer.
That's why the unit test implemented `NoResolvers`.

However! There is currently no scenario where we don't pass an external resolver in our cases; the only one is the canonical test – and that's where I implemented it.

In any other use case, like a contract or rusk, we always have an external resolver, since we always have at least the core dusk abi to retrieve, for example, the address of contract from the contract itself, or the gas count, or the poseidon hash etc.
So when we test such contract, we have to provide a "mock" resolver that exports those functions, and when we test rusk calling such contract, we're actually passing the `RuskResolver`.

So there is no need to export `NoResolvers` from canon_host.

So I would suggest to close this issue as wontfix, and improve the API in a later refactoring when everything is actually working and glued together.
